### ISSUE TITLE
Not working on Mozilla browser

### ISSUE THREAD

**Issue by nishant0131** [JohannesHoppe/angular-date-value-accessor#10]
Hi, 
This is quiet awesome, but unfortunately It is not not showing date picking functionality on Mozilla firefox.

**Comment by timbru31** [comment]
Heads up, seems like it's coming _soon_. Nightly >=55 has the datepicker enabled per default: https://bugzilla.mozilla.org/show_bug.cgi?id=1366188

**Comment by JohannesHoppe** [comment]
I love problems that solve themselves! :+1: :sunglasses:
