### ISSUE TITLE
An error:  ValueAsDate is not a date.

### ISSUE THREAD

**Issue by Reuno92** [JohannesHoppe/angular-date-value-accessor#12]
Hi,
I've a message and I don't understand.
I need someone to explain to me what I'm doing wrong.

My value is : "1994-01-01"
And I've a error like :

```
TypeError: Value being assigned to HTMLInputElement.valueAsDate is not a date.
```

**Comment by JohannesHoppe** [comment]
Looks like HTMLInputElement::valueAsDate setter support for type=date is not there. Please try this with another browser. 

see also https://github.com/JohannesHoppe/angular-date-value-accessor/issues/2
