### ISSUE TITLE
issue on Angular v7

### ISSUE THREAD

**Issue by aravindkr86** [JohannesHoppe/angular-date-value-accessor#14]
`<div class="form-group">
   <label>Payment Date</label>
     <input type="date" placeholder="Payment Date"   class="form-control showCalenderInline"   
      formControlName="payment_date" useValueAsDate  #payment_date  
      [(ngModel)]="paymentdata.payment_date"  >
 </div>`

> On page load the date value is not getting rendered
![Capture p](https://user-images.githubusercontent.com/43983217/55709503-116a6600-5a06-11e9-9fc3-98353d022431.JPG)

**Comment by JohannesHoppe** [comment]
Please provide an example on stackblitz.com so that we can reproduce this issue.

**Comment by JohannesHoppe** [comment]
Works in N8 for me!
