### ISSUE TITLE
allow type time and datetime-local

### ISSUE THREAD

**Issue by La-source** [JohannesHoppe/angular-date-value-accessor#15]
Hello,

I wanted to use the directive on a datetime-local type input unfortunately I got the error:

> InvalidStateError: Failed to set the 'valueAsDate' property on 'HTMLInputElement': This input element does not support Date values.

Whereas this input is quite a date type input. It will be very useful to be able to bear it.

**Comment by JohannesHoppe** [comment]
Can you provide a full example on stackblitz?

**Comment by La-source** [comment]
https://stackblitz.com/edit/angular-cfkhwi

I work with Google Chrome (version 79) to test the stackblitz link I use edge to confirm access and I see that on Edge it works well ...

**Comment by JohannesHoppe** [comment]
source: https://medium.com/@jonrimmer/fun-with-input-type-datetime-local-291bc29fac3c

As stated, `datetime-local` is not designed to have a `valueAsDate` property. The support of `datetime-local` is definitely not a functionality I need. But if you find a nice other solution, I would be happy to merge it.

**Comment by JohannesHoppe** [comment]
![reactive-works-local](https://user-images.githubusercontent.com/640639/100861195-c7af7880-3491-11eb-8dc2-95ede1171bba.gif)

The latest version finally ships with support for timezone / local dates!
The new accessor is called `LocalDateValueAccessor`.
Read more at:

**https://github.com/JohannesHoppe/angular-date-value-accessor/releases/tag/v.1.2.0**
