### ISSUE TITLE
Compatibility with Angular 9

### ISSUE THREAD

**Issue by juerggnos** [JohannesHoppe/angular-date-value-accessor#16]
Hello,

I'm trying to upgrade a project from angular 8 to 9 which uses this angular-date-value-accessor. Unfortunately compilation fails because Renderer (deprecated and replaced (with Renderer2) since Angular 4 and removed since Angular 9) is imported from @angular/core module.

Would it be possible to provide a new version of this angular-date-value-accessor which is compatible with Angular 9?

**Comment by JohannesHoppe** [comment]
Thanks for the info! Do you mind creating a pull request?! 🙂👍

**Comment by juerggnos** [comment]
Pull request created, was not able to link it with the issue. Here it is: https://github.com/JohannesHoppe/angular-date-value-accessor/pull/17

**Comment by JohannesHoppe** [comment]
Awesome! I will merge on Monday! 👍

**Comment by schonbachler** [comment]
Which Monday?

**Comment by juerggnos** [comment]
Cool, the pull request was merged. Thank you! When will a new version be published?

**Comment by JohannesHoppe** [comment]
I have looked at my ancient code and am amazed that it seems to work at all. The whole thing was built at a time when ng-packagr did not even exist. Whew... I think there's no way around it, there's still additional work to be done...

**Comment by JohannesHoppe** [comment]
...in example, the package.json is taking most of the generated files in account, but not the `module.ngfactory.js` and friends. I really don't know if this would break thinks or not. Additionally, the package breaks literally every aspect of the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/).

Right now I'm not confident enough to publish this to npm.

**Comment by JohannesHoppe** [comment]
But I'm on it now! 😄

**Comment by JohannesHoppe** [comment]
@schonbachler I just pushed a preview version (`1.0.0-rc.1`) to NPM. It's made on top of Angular 9, [without Ivy](https://angular.io/guide/creating-libraries#publishing-your-library). Could you please check if it works for you?!

The demo works, but I wasn't able to successfully execute the tests...
