### ISSUE TITLE
Tests are broken in 1.0.0-rc.2

### ISSUE THREAD

**Issue by JohannesHoppe** [JohannesHoppe/angular-date-value-accessor#19]
I would like to fix the tests before the final version 1 is released. Currently I have no idea why the tests don't work...

**Comment by rijkt** [comment]
I managed to solve this by wrapping a fakeAsync around all the tests and adding  tick() and detectChanges() calls as described in [this issue](https://github.com/angular/angular/issues/7409). I do however not understand what caused the tests to break. It wasn't the upgrade to Angular 9, they were green at that revision. Something to do with the new package structure/configuration?

**Comment by JohannesHoppe** [comment]
The old tests were based on Angular 2 and a lot has happened since then, I really have no idea what change brought the problem in.  In any case I am very thankfull for your help and will try out your PR right now!  👍
