### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by dagerber** [JohannesHoppe/angular-date-value-accessor#2]
Works great on modern browsers. Do you plan support for IE10/11 that have no support for IE?

**Comment by JohannesHoppe** [comment]
Yes and no. This should be done with a polyfill.
There are a plenty of them out there. I can include one by default, if you find a nice one.

**Comment by patrickmichalina** [comment]
@dagerber type="date" isn't supported in IE like it is in Chrome

**Comment by JohannesHoppe** [comment]
Sure, that's why should find a polyfill to fix that.

**Comment by d-koppenhagen** [comment]
See also here: https://www.npmjs.com/package/date-input-polyfill

**Comment by JohannesHoppe** [comment]
That one looks pretty nice! I will take a look...

**Comment by JohannesHoppe** [comment]
see also: https://github.com/JohannesHoppe/angular-date-value-accessor/issues/10 (Not working on Mozilla browser)

Solution for IE and Firefox would be a polyfill. Not a big deal, but I'm lagging time right now. I will have to provide a solution before our book-release (2017-05-22, http://angular-buch.com).

**Comment by JohannesHoppe** [comment]
If anybody needs this urgently, I will accept any pull request! 😉

**Comment by JohannesHoppe** [comment]
**The official recommendation is to use a polyfill.** 
I will update the README to point this out.

https://www.npmjs.com/package/date-input-polyfill

**Comment by JohannesHoppe** [comment]
<img width="957" alt="ie11" src="https://user-images.githubusercontent.com/640639/100903603-635adc00-34c6-11eb-89f5-c24e2576d3ac.png">

Please refer to this commit, if you want to enable IE11 support:
https://github.com/JohannesHoppe/angular-date-value-accessor/commit/2a95a7765b87950b3ae2848a3bbb6b4b265abf34

1. compile in ES5
2. adjust .browserslistrc
3. add the polyfill

`LocalDateValueAccessor` works as expected. Please note that all input fields operate in local time. This means that `DateValueAccessor` does not behave as specified. (I won't fix this! 😎 )

**Comment by JohannesHoppe** [comment]
@spierala commented on 2a95a77

> @JohannesHoppe
> In my IE11 the inputs stay empty:
> ![image](https://user-images.githubusercontent.com/1272446/100915511-bfc4f800-34d4-11eb-850b-6f646e6f78d4.png)
> 
> There are no errors in the console.
> 
> However I can select days. When selecting 1st december 2020 I can see the same as in your IE screenshot.
> But in my opinion the screenshot shows that none of the two DateValueAccessors works as expected...
> 
> ![image](https://user-images.githubusercontent.com/1272446/100916123-a1abc780-34d5-11eb-9e84-50e0b6febe03.png)

**Comment by JohannesHoppe** [comment]
@spierala I was happy too soon. You are right, the input fields are empty at the beginning, that shouldn't be the case.

I tested out https://github.com/KreutzerCode/configurable-date-input-polyfill from @KreutzerCode. This code base is under active development. See https://github.com/JohannesHoppe/angular-date-value-accessor/commit/485887220b02c64c686e43a23df38a6e2c75a3fa and the demo here:
https://johanneshoppe.github.io/angular-date-value-accessor/

This implementation seems to handle the UTC of the DateValueAcessor date correctly:

<img width="953" alt="Screen Shot 2020-12-02 at 20 54 22" src="https://user-images.githubusercontent.com/640639/100925082-cc9c1880-34e1-11eb-9cd0-39a21cb0c443.png">

Unfortunately the input fields are still empty at the beginning...

Did I overlook another problem?

**Comment by JohannesHoppe** [comment]
obsolete, since Angular 13

see #29, #30, #31
