### ISSUE TITLE
Angular 10 / tslib 2.0.0 support

### ISSUE THREAD

**Issue by d-koppenhagen** [JohannesHoppe/angular-date-value-accessor#21]
Updating an existing project with latest Angular CLI (10.0.0) leads to the following output when the project contains the `date-value-accessor` package as dependency:

```
                  Package "angular-date-value-accessor" has an incompatible peer dependency to "tslib" (requires "^1.10.0", would install "2.0.0").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/private/var/folders/7n/fqslh59s19v764fsyc2k8r1c0000gn/T/ng-hWI4lO/angular-errors.log" for further details.
```

It can be proceeded anyway when using the `--force` flag.

However, in the Future, the `angular-date-value-accessor` should be updated to support Angular 10 with tslib 2.0.0

**Comment by JohannesHoppe** [comment]
@d-koppenhagen v.1.1.0 is out. Could you double-check that everything works smoothly?
