### ISSUE TITLE
Github Actions: Unit test broken

### ISSUE THREAD

**Issue by JohannesHoppe** [JohannesHoppe/angular-date-value-accessor#25]
see https://github.com/JohannesHoppe/angular-date-value-accessor/runs/1479854470

@spierala

**Comment by spierala** [comment]
@JohannesHoppe can you try this in package.json?:
    
"test": "ng test --project date-value-accessor --watch=false --browsers=ChromeHeadless",

**Comment by spierala** [comment]
@JohannesHoppe 
I see it works now :)

Ideally the status badge links directly to https://github.com/JohannesHoppe/angular-date-value-accessor/actions?query=workflow%3ATests

Then it's really high end ;)

**Comment by JohannesHoppe** [comment]
Now it looks perfect! 😄 

see https://github.com/JohannesHoppe/angular-date-value-accessor/commit/1357c89c5944761ba6498b638d6238f9a2c2e717
bug fixed via https://github.com/JohannesHoppe/angular-date-value-accessor/commit/e82f8e3907c24f51c0c30c01ffc500345eebaacd
