### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by Anteru** [JohannesHoppe/angular-date-value-accessor#30]
The library is currently marked as compatible with Angular ~12, which prevents users to update to Angular 13 (released today.)

**Comment by JohannesHoppe** [comment]
Confimed, this will be the next task after #29.

**Comment by JohannesHoppe** [comment]
#29 is done, PR #30 is ready to be merged

I just pushed angular-date-value-accessor@2.0.0-rc.0 to npm.This version support Angular 13. @Anteru , do you mind testing it in our project?

**Comment by Anteru** [comment]
While I can't try it on _our_ project ;), I tried it in my project and it seems to work fine. Thanks a lot for the timely fix!

**Comment by JohannesHoppe** [comment]
I meant "your". 😉
Many thanks for the feedback! 👍
