### ISSUE TITLE
issue on Angular v4.0.1

### ISSUE THREAD

**Issue by hbweb** [JohannesHoppe/angular-date-value-accessor#9]
hi - for some reason the date does not bind for input type="date" in Reactive Form.  I use the your demo in Angular 4 but it does not work either. 
Any idea what is happening?  Thanks.
![gov-elements-year-field](https://cloud.githubusercontent.com/assets/242059/25093604/dcfb6d0a-238a-11e7-8b4a-b88e3dda7bfe.gif)

**Comment by JohannesHoppe** [comment]
In your gif  I see a working demo. this is a date-object, formatted as a ISO-String (e.g. `"2016-09-15T00:00:00.000Z"`). Everything is fine.

Without the directive you would see `"2016-09-15"` - which is a pure string!

**Comment by hbweb** [comment]
Hi @JohannesHoppe  - thanks for getting back to me. Yes, date object does seem to get updated when use enter the value in input element. However, it the input date does not initialised when the form load. 
We tried to set the date value on the page load

Typescript:

```

this.release2 = new Release('2.0.0', 'proprioception-reinforcement', new Date('2016-09-15'));

this.myForm2 = this.fb.group({
      version: [this.release2.version],
      name: [this.release2.name],
      releaseDate: [this.release2.releaseDate]
    });
```

Template

```
<form [formGroup]="myForm2">
        <label>Version:</label> <input type="text" formControlName="version">
        <label>Name:</label> <input type="text" formControlName="name">
        <label>Relase date:</label> <input type="date" formControlName="releaseDate" useValueAsDate>
      </form>
```

It should show '15-09-2016' instead of 'DD-MM-YYYY' on the page load.

Hope it makes sense.

**Comment by JohannesHoppe** [comment]
I see... looks like a bug.

**Comment by hbweb** [comment]
Sorry about that. Did you manage to replicate the issue on Angular v4? Cheers

**Comment by JohannesHoppe** [comment]
I can't promise an ETA, a lot of my OSS projects have pending issues! :-/
